---
title: "Apendix_generator"
author: "Matej Nemec"
date: "8/1/2022"
output: html_document
---
libs
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("rjson")
```

Set working directory to the location of this notebook.
```{r wd}
try({
  dr = getSrcDirectory()[1]
})
#when sourcing the file
try({
  dr = dirname(rstudioapi::getActiveDocumentContext()$path)
})
#for running code directly in rstudio
setwd(dr) #set for usage as a script/running lines
knitr::opts_knit$set(root.dir = dr) #set for R markdown chunk execution
```

functions

```{r fnc}
recur_unpack = function(pars, df, todel) {
  par_rows = df[df$pop %in% pars, ]
  new_pars = c()
  for (r in 1:nrow(par_rows)) {
    if (par_rows[r, 'pop'] %in% df[, 'parent_pop']) {
      par_row = par_rows[r, ]
      children_rows = df[df$parent_pop == par_row$pop, ]
      children_rows$relative_cnt = children_rows$relative_cnt * par_row$relative_cnt
      for (i in 1:nrow(children_rows)) {
        for (k in 1:ncol(children_rows)) {
          #there is definitely a way to do this better
          if (is.na(children_rows[i, k])) {
            children_rows[i, k] = par_row[1, k]
          }
        }
      }
      df[rownames(children_rows), ] = children_rows
      children = children_rows$pop
      for (child in children) {
        if (nrow(df[df$parent_pop %in% child, ]) != 0) {
          new_pars = c(new_pars, child)
        }
        todel = c(todel, as.integer(rownames(par_row)))
      }
    }
    if (r == nrow(par_rows) &&
        length(new_pars) == 0) {
      return(df[-unique(todel), ])
    }
  }
  recur_unpack(new_pars, df, todel)
}
```

Unpack phenotypes.

```{r pheno_unpack}
pheno = read.csv('phenotypes_noAFonly.csv',
                 sep = ',',
                 fileEncoding = "UTF-8-BOM")
todel = c()
pheno = recur_unpack(c('base'), pheno, todel)
write.csv(pheno,'pheno_unpacked.csv') 
```

read spectra

```{r spec}
spctr = fromJSON(file = "panel1_lymph_subtracted_fixed.json")
spectra = matrix(ncol = 64, nrow = length(spctr))
spec_names = c()
for (i in 1:length(spctr)) {
  spectra[i, ] = spctr[[i]]$spectrum$mS
  spec_names = c(spec_names, spctr[[i]]$antigen)
}
colnames(spectra) = spctr[[1]]$spectrum$channels
rm(spctr)
rownames(spectra) = spec_names
nspectra = nrow(spectra)
ndetects = ncol(spectra)
```

```{r exprob}
stronk = c(2, 3, 9, 14, 17, 21)
uncertainty=1
res = list()
spec_nms = row.names(spectra)
nspectra = nrow(spectra)
n=100
n_pheno = nrow(pheno)
pheno[is.na(pheno)] = 0
rownames(pheno) = paste0(pheno$parent_pop, pheno$pop)
bkp = rownames(pheno)
relative_cnt = pheno$relative_cnt * (1 / sum(pheno$relative_cnt))
counts_pheno = pheno$relative_cnt
pheno = pheno[, -c(1:3)]
dead = pheno #duplicate
rownames(dead) = paste0(rep('dead_', n_pheno), rownames(pheno))
pheno[, 'LIVE DEAD Blue'] = rep(0, n_pheno) #LD expr for live cells is ~0
pheno = pheno[, rownames(spectra)]
cnts_dead = counts_pheno * runif(n_pheno, 0.1, 0.25) #amount of dead cells for each phenotype 10-25%
cnts_dead = cnts_dead / sum(cnts_dead)
  
#Generate probability matrices separately for live and dead cells
spectra = spectra / sqrt(rowSums(spectra ^ 2)) #normalize spectra to unit vector(magnitude=1) this is already done if spectra from panelbuilder
d = ncol(spectra) #number of detectors
exp_prob_mtx_normal = pheno[rep(1:n_pheno , round(counts_pheno * n *
                                                      0.825)), ]
write.csv(exp_prob_mtx_normal,'ext_prob.csv') 
```

dead cells

```{r exprob_dead}
  exp_prob_mtx_dead = dead[rep(1:n_pheno , round(cnts_dead * n * 0.175)), ]#maybe LD expression should increase(complement) with how dead the cells are - eq. with decrease in expr proportion increase LD expr.
  dead_exp=runif(nrow(exp_prob_mtx_dead), 0.3, 0.6)
  exp_prob_mtx_dead = exp_prob_mtx_dead * dead_exp #expression magnitude for dead cells 30-60%
  dead_exp = (1-dead_exp) + runif(nrow(exp_prob_mtx_dead), 0.3, 0.5)#LD expr for dead cells 60-100%
  dead_exp[dead_exp>1]=1
  exp_prob_mtx_dead[, 'LIVE DEAD Blue']=dead_exp
  exp_prob_mtx_dead = exp_prob_mtx_dead[, rownames(spectra)]
  full_prob_mtx = rbind(exp_prob_mtx_normal, exp_prob_mtx_dead)
```

expression/strong markers

```{r}
#Appropriately amplify the expression of strong markers
  nr = nrow(full_prob_mtx) #get the actual number of cells (probably !=n because of rounding)
  weak = (1:ncol(full_prob_mtx))[!(1:ncol(full_prob_mtx) %in% stronk)]
  k_stronk = length(stronk)
  k_weak = nrow(spectra) - k_stronk
  
  #Generate expression abundance matrix from probability matrices
  exprs_stronk =
    10 ^ ((4-uncertainty) + uncertainty * (matrix(
      rbinom(nr * k_stronk, 1, as.matrix(full_prob_mtx[, stronk])), nr, k_stronk
    ) + rnorm(nr * k_stronk, sd = 0.2)))
  exprs_weak =
    10 ^ (2 + 2 * (matrix(
      rbinom(nr * k_weak, 1, as.matrix(full_prob_mtx[, weak])), nr, k_weak
    ) + rnorm(nr * k_weak, sd = 0.2)))
  exprs = matrix(,
                 nrow = nrow(full_prob_mtx),
                 ncol = ncol(full_prob_mtx))
  exprs[, stronk] = exprs_stronk
  exprs[, weak] = exprs_weak
  rownames(exprs) = rownames(full_prob_mtx)
  colnames(exprs) = colnames(full_prob_mtx)
```

